## Comments

- Code must be self-explanatory: reach for clear names, small functions, and types before a comment.
- Do not add comments by default. A comment is a last resort and explains only *why* something is done, never *what* the code does.
- When you encounter an obsolete, redundant, or "what" comment, delete it.
- Delete section banners and navigation comments unless they explain a non-obvious boundary.
- Delete comments that narrate the next line, assertion, or obvious test setup; prefer clearer test names and variable names.
- Keep PHPDoc only when it carries type information, public API intent, static-analysis value, or a non-obvious constraint.
- Keep comments that explain framework quirks, ordering requirements, test timing, cache or build behavior, performance traps, or other constraints that are hard to infer from the code alone.

## Git & pull requests

- Never credit the agent. No `Co-Authored-By` trailer and no "generated by" attribution in commit messages or pull request descriptions.
- Make meaningful commits: one logical change per commit with a conventional-commit subject (`feat:`, `fix:`, `chore:`, `refactor:`, `test:`, `docs:`). Squash throwaway "wip" commits before opening a pull request.
- Never commit agent planning artifacts. Keep `docs/superpowers/`, `.superpowers/`, `.agents/`, `.codex/`, `.junie/`, and similar scratch files out of commits, even when they informed the work.
- Keep pull request descriptions compact: what changed and why, in a few lines. No filler.

## Package development under Testbench

- This package is developed with Orchestra Testbench, not a full Laravel app. There is no application skeleton in the repository.
- `artisan` in the package root is a one-line shim that requires `vendor/bin/testbench`, so `php artisan <command>` and `vendor/bin/testbench <command>` are equivalent — both boot the Testbench skeleton with this package's service provider registered. If `artisan` is missing, `vendor/bin/testbench` always works, and a `boost:*` or `mcp:*` command recreates the shim.
- `base_path()` points at the Testbench skeleton (`vendor/orchestra/testbench-core/laravel`), not at the package root, so never reach package files through it — use `Orchestra\Testbench\package_path()`. The one exception is `boost:*` and `mcp:*` commands, where this package deliberately rebases `base_path()` to the package root so Boost writes into the repository; nothing else should rely on that.
- Configuration for the test application lives in `testbench.yaml`.
- Extra app code for tests belongs in `workbench/`, which requires `Workbench\App\` and `Workbench\Database\Factories\` `autoload-dev` psr-4 entries, plus a `workbench:` block in `testbench.yaml` for providers and routes. If the package has neither, keep test-only app code under `tests/`.
- Run the test suite with `composer test`, or `vendor/bin/pest` / `vendor/bin/phpunit` when no script is defined.
- Regenerate `CLAUDE.md` and `AGENTS.md` with `vendor/bin/testbench boost:update` after editing anything in `.ai/guidelines/`.
